version: "3.8"
services:
  postgres:
    image: postgres:15.14-alpine3.21
    ports:
      - 5433:5432
    env_file:
      - .env.development
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nest-init

volumes:
  postgres:
    name: combs-and-clippers-db

networks:
  nest-init: